export const tableCols = [
  [
    "Symbol",
    "Size",
    "Entry Proce",
    "Liq.price",
    "Margin Ratio",
    "Margin",
    "PNL(ROE%)",
    "Close All Positions",
    "TP/SL for Position",
  ],
  [
    "Time",
    "Symbol",
    "Type",
    "Side",
    "Average",
    "Price",
    "Executed",
    "Amount",
    "Reduce",
    "Post Only",
    "Trigger Conditions",
  ],
  [
    "Time",
    "Symbol",
    "Side",
    "Price",
    "Quantity",
    "Fee",
    "Role",
    "Realized Profit",
  ],
  ["Time", "Type", "Amount", "Asset", "Symbol"],
  [],
];
export const tabContents = [
  "",
  "You have no order history.",
  "You have no trades.",
  "You have no trades.",
  "No data.",
];
